---
#driver:
#  name: docker
#  dockerfile: test/Dockerfile-centos66
#  provision_command: curl -L http://www.chef.io/chef/install.sh | bash
#  driver_config:
#    publish_all: true

platforms:
#- name: centos-5
- name: centos-6
#- name: centos-7
#- name: fedora
#- name: ubuntu-12
#  run_list:
#  - recipe[apt]
#- name: ubuntu-14
#  run_list:
#  - recipe[apt]
#- name: debian
#  run_list:
#  - recipe[apt]

provisioner:
  name: chef_zero
  require_chef_omnibus: '11'
  data_bags_path: 'test/integration/data_bags'

suites:
- name: default
  run_list:
  - recipe[ellktest]
